import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

const PYTHON_CARDS: Record<string, { description: string; code_example: string; exercise: string; difficulty: number; subtitle?: string }> = {
  'enumerate()': { description: 'Retorna um iterável de tuplas (índice, valor) para cada elemento de uma sequência.', code_example: 'for i, fruta in enumerate(frutas):\n    print(f"{i}: {fruta}")', exercise: 'Dada a lista ["maçã", "banana", "uva"], use enumerate() para imprimir cada item com seu índice.', difficulty: 1, subtitle: 'Itera com índice' },
  'zip()': { description: 'Agrega elementos de múltiplos iteráveis em tuplas, parando no iterável mais curto.', code_example: 'nomes = ["Ana", "Bob"]\nidades = [25, 30]\nfor nome, idade in zip(nomes, idades):\n    print(nome, idade)', exercise: 'Dadas duas listas (nomes e idades), use zip() para imprimir nome e idade juntos.', difficulty: 1, subtitle: 'Agrega iteráveis' },
  'range()': { description: 'Gera uma sequência de números inteiros, útil em loops for.', code_example: 'for i in range(5):\n    print(i)  # 0, 1, 2, 3, 4\n\nfor i in range(2, 8, 2):\n    print(i)  # 2, 4, 6', exercise: 'Use range() para imprimir os números pares de 0 a 20.', difficulty: 1, subtitle: 'Sequência numérica' },
  'len()': { description: 'Retorna o número de itens (comprimento) de um objeto.', code_example: 'lista = [1, 2, 3, 4]\nprint(len(lista))  # 4\n\ntexto = "Hello"\nprint(len(texto))  # 5', exercise: 'Crie uma lista com 5 elementos e use len() para imprimir seu tamanho.', difficulty: 1, subtitle: 'Tamanho de objeto' },
  'sorted()': { description: 'Retorna uma nova lista ordenada a partir de um iterável.', code_example: 'nums = [3, 1, 4, 1, 5]\nprint(sorted(nums))  # [1, 1, 3, 4, 5]\n\nprint(sorted(nums, reverse=True))  # [5, 4, 3, 1, 1]', exercise: 'Dada a lista [9, 2, 7, 4], use sorted() para ordenar em ordem decrescente.', difficulty: 1, subtitle: 'Ordena iterável' },
  'map()': { description: 'Aplica uma função a cada item de um iterável e retorna um iterador.', code_example: 'nums = [1, 2, 3, 4]\ndobro = list(map(lambda x: x * 2, nums))\nprint(dobro)  # [2, 4, 6, 8]', exercise: 'Use map() para converter ["1", "2", "3"] em uma lista de inteiros.', difficulty: 2, subtitle: 'Aplica função a cada item' },
  'filter()': { description: 'Filtra elementos de um iterável usando uma função que retorna True/False.', code_example: 'nums = [1, 2, 3, 4, 5, 6]\npares = list(filter(lambda x: x % 2 == 0, nums))\nprint(pares)  # [2, 4, 6]', exercise: 'Use filter() para manter apenas números maiores que 10 em [5, 12, 8, 15, 3].', difficulty: 2, subtitle: 'Filtra iterável' },
  'lambda': { description: 'Cria funções anônimas (sem nome) de uma linha.', code_example: 'soma = lambda a, b: a + b\nprint(soma(3, 5))  # 8\n\nquadrado = lambda x: x ** 2\nprint(quadrado(4))  # 16', exercise: 'Crie uma lambda que recebe dois números e retorna o produto deles.', difficulty: 2, subtitle: 'Função anônima' },
  'list comprehension': { description: 'Cria listas de forma concisa usando expressões dentro de colchetes.', code_example: 'pares = [x for x in range(10) if x % 2 == 0]\nprint(pares)  # [0, 2, 4, 6, 8]\n\nquadrados = [x**2 for x in range(5)]\nprint(quadrados)  # [0, 1, 4, 9, 16]', exercise: 'Use list comprehension para criar uma lista com os cubos de 1 a 5.', difficulty: 2, subtitle: 'Lista por expressão' },
  'dict comprehension': { description: 'Cria dicionários de forma concisa usando expressões dentro de chaves.', code_example: 'quadrados = {x: x**2 for x in range(5)}\nprint(quadrados)  # {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}', exercise: 'Crie um dict comprehension onde a chave é o número e o valor é o dobro, para 1 a 5.', difficulty: 2, subtitle: 'Dict por expressão' },
  'set()': { description: 'Cria um conjunto (set) — coleção não ordenada de elementos únicos.', code_example: 'nums = [1, 2, 2, 3, 3, 3]\nunicos = set(nums)\nprint(unicos)  # {1, 2, 3}', exercise: 'Dada a lista ["a", "b", "a", "c"], use set() para remover duplicatas.', difficulty: 1, subtitle: 'Coleção de únicos' },
  'f-string': { description: 'Formatação de strings com interpolação de variáveis usando f"..."', code_example: 'nome = "Maria"\nidade = 25\nprint(f"{nome} tem {idade} anos")\n\npi = 3.14159\nprint(f"Pi: {pi:.2f}")  # Pi: 3.14', exercise: 'Use f-string para formatar: "O produto de 7 e 8 é 56".', difficulty: 1, subtitle: 'Interpolação de strings' },
  '*args': { description: 'Permite passar número variável de argumentos posicionais para uma função.', code_example: 'def soma(*args):\n    return sum(args)\n\nprint(soma(1, 2, 3))    # 6\nprint(soma(10, 20))     # 30', exercise: 'Crie uma função com *args que retorna a média de todos os números passados.', difficulty: 2, subtitle: 'Args variáveis posicionais' },
  '**kwargs': { description: 'Permite passar número variável de argumentos nomeados (keyword) para uma função.', code_example: 'def criar_perfil(**kwargs):\n    for chave, valor in kwargs.items():\n        print(f"{chave}: {valor}")\n\ncriar_perfil(nome="Ana", idade=25)', exercise: 'Crie uma função com **kwargs que imprime apenas os valores maiores que 10.', difficulty: 2, subtitle: 'Args variáveis nomeados' },
  'decorator': { description: 'Função que modifica o comportamento de outra função sem alterar seu código.', code_example: 'def timer(func):\n    def wrapper(*args, **kwargs):\n        print("Iniciando...")\n        return func(*args, **kwargs)\n    return wrapper\n\n@timer\ndef saudacao():\n    print("Olá!")', exercise: 'Crie um decorator que imprime "antes" e "depois" da execução da função.', difficulty: 3, subtitle: 'Modifica função' },
  'generator': { description: 'Função que usa yield para produzir uma sequência de valores sob demanda.', code_example: 'def contador(max):\n    n = 0\n    while n < max:\n        yield n\n        n += 1\n\nfor i in contador(5):\n    print(i)  # 0, 1, 2, 3, 4', exercise: 'Crie um generator que produz os números de Fibonacci até um limite.', difficulty: 3, subtitle: 'Produz sob demanda' },
  'try/except': { description: 'Tratamento de erros — captura exceções para evitar que o programa quebre.', code_example: 'try:\n    resultado = 10 / 0\nexcept ZeroDivisionError:\n    print("Não é possível dividir por zero!")\nfinally:\n    print("Fim.")', exercise: 'Use try/except para tratar um IndexError ao acessar lista[10] em uma lista de 3 itens.', difficulty: 2, subtitle: 'Tratamento de erros' },
  'with open()': { description: 'Gerenciador de contexto para abrir arquivos — fecha automaticamente ao sair do bloco.', code_example: 'with open("arquivo.txt", "r") as f:\n    conteudo = f.read()\n    print(conteudo)', exercise: 'Use with open() para escrever "Hello World" em um arquivo chamado saida.txt.', difficulty: 2, subtitle: 'Gerenciador de arquivo' },
  'isinstance()': { description: 'Verifica se um objeto é uma instância de uma classe ou tipo.', code_example: 'x = 42\nprint(isinstance(x, int))    # True\nprint(isinstance(x, str))    # False\nprint(isinstance(x, (int, float)))  # True', exercise: 'Use isinstance() para verificar se a variável é uma lista ou tupla.', difficulty: 1, subtitle: 'Verifica tipo' },
  'any() / all()': { description: 'any() retorna True se algum elemento for truthy. all() retorna True se todos forem truthy.', code_example: 'nums = [0, 1, 2, 3]\nprint(any(n > 2 for n in nums))  # True\nprint(all(n > 0 for n in nums))  # False', exercise: 'Use all() para verificar se todos os números em [2, 4, 6, 8] são pares.', difficulty: 2, subtitle: 'Verifica elementos' },
  'split()': { description: 'Divide uma string em uma lista de substrings usando um separador.', code_example: 'frase = "Python é incrível"\nprint(frase.split())  # ["Python", "é", "incrível"]\n\ndados = "a,b,c"\nprint(dados.split(","))  # ["a", "b", "c"]', exercise: 'Use split() para separar "10-20-30" pelo hífen e converter para inteiros.', difficulty: 1, subtitle: 'Divide string' },
  'join()': { description: 'Une elementos de um iterável em uma string usando um separador.', code_example: 'palavras = ["Python", "é", "legal"]\nprint(" ".join(palavras))  # "Python é legal"\n\nnums = ["1", "2", "3"]\nprint("-".join(nums))  # "1-2-3"', exercise: 'Use join() para unir ["a", "b", "c"] com vírgula e espaço.', difficulty: 1, subtitle: 'Une string' },
  'append()': { description: 'Adiciona um elemento ao final de uma lista.', code_example: 'frutas = ["maçã", "banana"]\nfrutas.append("uva")\nprint(frutas)  # ["maçã", "banana", "uva"]', exercise: 'Crie uma lista vazia e use append() para adicionar 5 números.', difficulty: 1, subtitle: 'Adiciona à lista' },
  'dict.get()': { description: 'Retorna o valor de uma chave no dicionário, ou um valor padrão se não existir.', code_example: 'dados = {"nome": "Ana", "idade": 25}\nprint(dados.get("nome"))       # "Ana"\nprint(dados.get("email", "N/A"))  # "N/A"', exercise: 'Use dict.get() para acessar a chave "telefone" com valor padrão "Não informado".', difficulty: 1, subtitle: 'Acesso seguro ao dict' },
  'class': { description: 'Define uma classe — molde para criar objetos com atributos e métodos.', code_example: 'class Pessoa:\n    def __init__(self, nome, idade):\n        self.nome = nome\n        self.idade = idade\n\n    def apresentar(self):\n        return f"Olá, sou {self.nome}"', exercise: 'Crie uma classe Calculadora com métodos soma() e subtrai().', difficulty: 2, subtitle: 'Define classe' },
  'super()': { description: 'Chama métodos da classe pai, útil em herança.', code_example: 'class Animal:\n    def __init__(self, nome):\n        self.nome = nome\n\nclass Cachorro(Animal):\n    def __init__(self, nome, raca):\n        super().__init__(nome)\n        self.raca = raca', exercise: 'Crie uma classe Filho que herda de Pai e usa super() no __init__.', difficulty: 3, subtitle: 'Chama classe pai' },
  '__init__()': { description: 'Método construtor da classe — chamado ao criar uma nova instância.', code_example: 'class Produto:\n    def __init__(self, nome, preco):\n        self.nome = nome\n        self.preco = preco\n\np = Produto("Camiseta", 29.90)', exercise: 'Crie uma classe Livro com __init__ recebendo título, autor e ano.', difficulty: 1, subtitle: 'Construtor da classe' },
  'import': { description: 'Importa módulos ou pacotes para usar no código.', code_example: 'import math\nprint(math.sqrt(16))  # 4.0\n\nfrom random import randint\nprint(randint(1, 10))\n\nfrom datetime import datetime\nprint(datetime.now())', exercise: 'Importe o módulo os e use os.getcwd() para imprimir o diretório atual.', difficulty: 1, subtitle: 'Importa módulo' },
  'if __name__ == "__main__"': { description: 'Bloco que só executa quando o arquivo é rodado diretamente, não quando importado.', code_example: 'def main():\n    print("Rodando como script principal")\n\nif __name__ == "__main__":\n    main()', exercise: 'Crie um arquivo com uma função e o bloco if __name__ para testá-la.', difficulty: 2, subtitle: 'Ponto de entrada' },
  'assert': { description: 'Verifica uma condição e levanta AssertionError se for falsa — útil para debug.', code_example: 'idade = -5\nassert idade >= 0, "Idade não pode ser negativa"', exercise: 'Use assert para verificar que uma lista não está vazia.', difficulty: 2, subtitle: 'Verificação de debug' },
}

const SQL_CARDS: Record<string, { description: string; code_example: string; exercise: string; difficulty: number; subtitle?: string }> = {
  'SELECT': { description: 'Consulta dados de uma ou mais tabelas no banco.', code_example: 'SELECT nome, email FROM usuarios WHERE ativo = true;', exercise: 'Escreva um SELECT para pegar nome e salário da tabela funcionarios.', difficulty: 1, subtitle: 'Consulta dados' },
  'WHERE': { description: 'Filtra registros com base em uma condição.', code_example: 'SELECT * FROM produtos WHERE preco > 100 AND estoque > 0;', exercise: 'Use WHERE para selecionar usuários com idade >= 18.', difficulty: 1, subtitle: 'Filtra registros' },
  'INNER JOIN': { description: 'Retorna registros que têm correspondência em ambas as tabelas.', code_example: 'SELECT u.nome, p.titulo\nFROM usuarios u\nINNER JOIN pedidos p ON u.id = p.usuario_id;', exercise: 'Faça um INNER JOIN entre departamentos e funcionarios pela coluna dept_id.', difficulty: 2, subtitle: 'Junção interna' },
  'LEFT JOIN': { description: 'Retorna todos os registros da tabela à esquerda e os correspondentes da direita.', code_example: 'SELECT u.nome, p.titulo\nFROM usuarios u\nLEFT JOIN pedidos p ON u.id = p.usuario_id;', exercise: 'Faça um LEFT JOIN entre usuarios e pedidos para mostrar todos os usuários mesmo sem pedidos.', difficulty: 2, subtitle: 'Junção externa esquerda' },
  'GROUP BY': { description: 'Agrupa registros que têm valores iguais em colunas especificadas.', code_example: 'SELECT departamento, COUNT(*) as total, AVG(salario) as media\nFROM funcionarios\nGROUP BY departamento;', exercise: 'Use GROUP BY para contar quantos produtos existem por categoria.', difficulty: 2, subtitle: 'Agrupa registros' },
  'HAVING': { description: 'Filtra grupos após o GROUP BY — como WHERE mas para agregações.', code_example: 'SELECT departamento, COUNT(*) as total\nFROM funcionarios\nGROUP BY departamento\nHAVING COUNT(*) > 5;', exercise: 'Use HAVING para mostrar categorias com mais de 10 produtos.', difficulty: 2, subtitle: 'Filtra grupos' },
  'ORDER BY': { description: 'Ordena o resultado por uma ou mais colunas.', code_example: 'SELECT nome, salario FROM funcionarios\nORDER BY salario DESC, nome ASC;', exercise: 'Ordene produtos por preço decrescente e depois por nome.', difficulty: 1, subtitle: 'Ordena resultado' },
  'INSERT INTO': { description: 'Insere novos registros em uma tabela.', code_example: 'INSERT INTO usuarios (nome, email, idade)\nVALUES ("Maria", "maria@email.com", 28);', exercise: 'Insira um novo produto com nome "Teclado", preço 150 e estoque 30.', difficulty: 1, subtitle: 'Insere registros' },
  'UPDATE': { description: 'Modifica registros existentes em uma tabela.', code_example: 'UPDATE produtos\nSET preco = preco * 1.1\nWHERE categoria = "Eletrônicos";', exercise: 'Use UPDATE para definir ativo = false para usuários com idade < 18.', difficulty: 1, subtitle: 'Atualiza registros' },
  'DELETE': { description: 'Remove registros de uma tabela.', code_example: 'DELETE FROM logs WHERE data < "2024-01-01";', exercise: 'Delete todos os pedidos com status "cancelado".', difficulty: 1, subtitle: 'Remove registros' },
  'COUNT()': { description: 'Conta o número de registros que atendem a uma condição.', code_example: 'SELECT COUNT(*) as total FROM usuarios;\nSELECT COUNT(DISTINCT cidade) FROM clientes;', exercise: 'Use COUNT() para contar quantos funcionários ganham mais de 5000.', difficulty: 1, subtitle: 'Conta registros' },
  'SUM()': { description: 'Calcula a soma de uma coluna numérica.', code_example: 'SELECT SUM(vendas) as total_vendas FROM relatorio_mensal;', exercise: 'Use SUM() para calcular o total gasto por cada cliente.', difficulty: 1, subtitle: 'Soma valores' },
  'AVG()': { description: 'Calcula a média de uma coluna numérica.', code_example: 'SELECT AVG(salario) as media_salarial FROM funcionarios;', exercise: 'Use AVG() para calcular a idade média dos usuários.', difficulty: 1, subtitle: 'Média de valores' },
  'MAX() / MIN()': { description: 'Retorna o maior ou menor valor de uma coluna.', code_example: 'SELECT MAX(salario), MIN(salario) FROM funcionarios;', exercise: 'Use MAX() e MIN() para encontrar o produto mais caro e mais barato.', difficulty: 1, subtitle: 'Valor máximo/mínimo' },
  'LIKE': { description: 'Busca padrões em strings usando % (qualquer coisa) e _ (um caractere).', code_example: 'SELECT * FROM usuarios WHERE nome LIKE "%Silva%";\nSELECT * FROM produtos WHERE codigo LIKE "PR_%%";', exercise: 'Use LIKE para encontrar emails que terminam com "@gmail.com".', difficulty: 1, subtitle: 'Busca por padrão' },
  'CASE WHEN': { description: 'Expressão condicional — como if/else no SQL.', code_example: 'SELECT nome, salario,\n  CASE\n    WHEN salario > 5000 THEN "Alto"\n    WHEN salario > 3000 THEN "Médio"\n    ELSE "Baixo"\n  END as faixa\nFROM funcionarios;', exercise: 'Use CASE WHEN para classificar notas: >= 7 "Aprovado", < 7 "Reprovado".', difficulty: 2, subtitle: 'Condicional SQL' },
  'DISTINCT': { description: 'Remove duplicatas do resultado.', code_example: 'SELECT DISTINCT cidade FROM clientes;', exercise: 'Use DISTINCT para listar todas as categorias únicas de produtos.', difficulty: 1, subtitle: 'Remove duplicatas' },
  'LIMIT': { description: 'Restringe o número de registros retornados.', code_example: 'SELECT * FROM produtos ORDER BY preco DESC LIMIT 10;', exercise: 'Use LIMIT para pegar os 5 usuários mais recentes.', difficulty: 1, subtitle: 'Limita resultados' },
  'BETWEEN': { description: 'Filtra valores dentro de um intervalo (inclusivo).', code_example: 'SELECT * FROM produtos WHERE preco BETWEEN 50 AND 200;', exercise: 'Use BETWEEN para encontrar pedidos feitos entre "2024-01-01" e "2024-06-30".', difficulty: 1, subtitle: 'Intervalo de valores' },
  'IN': { description: 'Filtra registros onde o valor está em uma lista.', code_example: 'SELECT * FROM usuarios WHERE cidade IN ("SP", "RJ", "BH");', exercise: 'Use IN para selecionar produtos das categorias "Eletrônicos", "Livros" e "Games".', difficulty: 1, subtitle: 'Lista de valores' },
  'COALESCE()': { description: 'Retorna o primeiro valor não nulo de uma lista.', code_example: 'SELECT nome, COALESCE(telefone, email, "Sem contato") as contato\nFROM clientes;', exercise: 'Use COALESCE() para substituir NULL em "desconto" por 0.', difficulty: 2, subtitle: 'Primeiro não nulo' },
  'ROW_NUMBER()': { description: 'Window function que numera linhas dentro de um grupo.', code_example: 'SELECT nome, departamento, salario,\n  ROW_NUMBER() OVER (PARTITION BY departamento ORDER BY salario DESC) as ranking\nFROM funcionarios;', exercise: 'Use ROW_NUMBER() para rankear produtos por vendas dentro de cada categoria.', difficulty: 3, subtitle: 'Numera linhas' },
}

const PANDAS_CARDS: Record<string, { description: string; code_example: string; exercise: string; difficulty: number; subtitle?: string }> = {
  'pd.read_csv()': { description: 'Lê um arquivo CSV e retorna um DataFrame.', code_example: 'import pandas as pd\ndf = pd.read_csv("dados.csv", sep=",", encoding="utf-8")\nprint(df.head())', exercise: 'Use pd.read_csv() para ler "vendas.csv" e mostrar as 10 primeiras linhas.', difficulty: 1, subtitle: 'Lê CSV' },
  'df.head()': { description: 'Mostra as primeiras linhas do DataFrame (padrão: 5).', code_example: 'df.head()      # primeiras 5 linhas\ndf.head(10)    # primeiras 10 linhas', exercise: 'Use df.head() para mostrar as 3 primeiras linhas do DataFrame.', difficulty: 1, subtitle: 'Primeiras linhas' },
  'df.describe()': { description: 'Gera estatísticas descritivas para colunas numéricas.', code_example: 'print(df.describe())\n# count, mean, std, min, 25%, 50%, 75%, max', exercise: 'Use df.describe() para ver estatísticas de um DataFrame de vendas.', difficulty: 1, subtitle: 'Estatísticas descritivas' },
  'df.info()': { description: 'Mostra resumo do DataFrame: tipos, não nulos, memória.', code_example: 'df.info()\n# <class \'pandas.core.frame.DataFrame\'>\n# RangeIndex: 1000 entries\n# nome     1000 non-null object\n# idade    998 non-null float64', exercise: 'Use df.info() para verificar colunas com valores nulos.', difficulty: 1, subtitle: 'Resumo do DataFrame' },
  'df.groupby()': { description: 'Agrupa dados por colunas e permite aplicar funções de agregação.', code_example: 'resultado = df.groupby("categoria").agg({\n    "valor": ["sum", "mean", "count"]\n}).reset_index()', exercise: 'Use groupby() para calcular a média de salário por departamento.', difficulty: 2, subtitle: 'Agrupa por coluna' },
  'df.merge()': { description: 'Combina dois DataFrames usando uma coluna chave (como SQL JOIN).', code_example: 'resultado = df1.merge(df2, on="id", how="left")', exercise: 'Use merge() para unir pedidos e clientes pela coluna cliente_id.', difficulty: 2, subtitle: 'Junção de DataFrames' },
  'df.pivot_table()': { description: 'Cria uma tabela dinâmica (pivot) com agregação.', code_example: 'pivot = df.pivot_table(\n    values="vendas",\n    index="regiao",\n    columns="mes",\n    aggfunc="sum"\n)', exercise: 'Crie uma pivot_table com média de nota por turma e disciplina.', difficulty: 3, subtitle: 'Tabela dinâmica' },
  'df.apply()': { description: 'Aplica uma função ao longo de um eixo (linhas ou colunas).', code_example: 'df["nome_upper"] = df["nome"].apply(str.upper)\ndf["dobro"] = df["valor"].apply(lambda x: x * 2)', exercise: 'Use apply() para criar uma coluna com o comprimento de cada string na coluna "nome".', difficulty: 2, subtitle: 'Aplica função' },
  'df.dropna()': { description: 'Remove linhas ou colunas com valores nulos.', code_example: 'df_clean = df.dropna()                    # remove qualquer nulo\ndf_clean = df.dropna(subset=["nome"])     # remove onde nome é nulo', exercise: 'Use dropna() para remover linhas onde a coluna "email" é nula.', difficulty: 1, subtitle: 'Remove nulos' },
  'df.fillna()': { description: 'Substitui valores nulos por um valor especificado.', code_example: 'df["idade"] = df["idade"].fillna(0)\ndf = df.fillna({"nome": "Desconhecido", "idade": 0})', exercise: 'Use fillna() para preencher nulos na coluna "nota" com a média.', difficulty: 1, subtitle: 'Preenche nulos' },
  'df.sort_values()': { description: 'Ordena o DataFrame por valores de uma ou mais colunas.', code_example: 'df.sort_values("idade", ascending=False)\ndf.sort_values(["departamento", "salario"], ascending=[True, False])', exercise: 'Ordene o DataFrame por vendas decrescente.', difficulty: 1, subtitle: 'Ordena DataFrame' },
  'df.loc[]': { description: 'Acessa linhas/colunas por label (nome).', code_example: 'df.loc[0, "nome"]              # valor específico\ndf.loc[df["idade"] > 18]     # filtro por condição\ndf.loc[:, ["nome", "idade"]]  # colunas específicas', exercise: 'Use loc[] para selecionar nome e email de todos os usuários ativos.', difficulty: 2, subtitle: 'Acesso por label' },
  'df.iloc[]': { description: 'Acessa linhas/colunas por posição (índice inteiro).', code_example: 'df.iloc[0]          # primeira linha\ndf.iloc[:5, :3]     # 5 primeiras linhas, 3 primeiras colunas\ndf.iloc[-1]         # última linha', exercise: 'Use iloc[] para pegar as 10 primeiras linhas e as 2 últimas colunas.', difficulty: 2, subtitle: 'Acesso por índice' },
  'df.query()': { description: 'Filtra DataFrame usando uma expressão string.', code_example: 'df.query("idade > 18 and cidade == \'SP\'")\ndf.query("vendas > media_vendas")', exercise: 'Use query() para filtrar produtos com preço > 100 e estoque > 0.', difficulty: 2, subtitle: 'Filtra com expressão' },
  'df.value_counts()': { description: 'Conta frequência de valores únicos em uma coluna.', code_example: 'df["cidade"].value_counts()\ndf["cidade"].value_counts(normalize=True)  # percentual', exercise: 'Use value_counts() para contar quantos pedidos existem por status.', difficulty: 1, subtitle: 'Conta valores únicos' },
  'df.rename()': { description: 'Renomeia colunas do DataFrame.', code_example: 'df = df.rename(columns={"nome_completo": "nome", "data_nasc": "nascimento"})', exercise: 'Use rename() para mudar "qtd" para "quantidade" e "vlr" para "valor".', difficulty: 1, subtitle: 'Renomeia colunas' },
  'df.drop()': { description: 'Remove linhas ou colunas do DataFrame.', code_example: 'df = df.drop(columns=["coluna_inutil"])\ndf = df.drop(index=[0, 1, 2])', exercise: 'Use drop() para remover a coluna "id_temporário".', difficulty: 1, subtitle: 'Remove colunas/linhas' },
  'pd.concat()': { description: 'Concatena DataFrames ao longo de um eixo (empilha ou junta lado a lado).', code_example: 'resultado = pd.concat([df1, df2], ignore_index=True)', exercise: 'Use pd.concat() para empilhar dois DataFrames de meses diferentes.', difficulty: 2, subtitle: 'Concatena DataFrames' },
  'df.isnull()': { description: 'Retorna booleanos indicando valores nulos.', code_example: 'df.isnull().sum()  # conta nulos por coluna\ndf.isnull().any()  # quais colunas têm nulos', exercise: 'Use isnull() para encontrar quantos valores nulos existem em cada coluna.', difficulty: 1, subtitle: 'Detecta nulos' },
  'df.duplicated()': { description: 'Identifica linhas duplicadas no DataFrame.', code_example: 'df.duplicated().sum()  # quantas duplicatas\ndf.drop_duplicates()   # remove duplicatas', exercise: 'Use duplicated() para contar e drop_duplicates() para remover duplicatas.', difficulty: 1, subtitle: 'Detecta duplicatas' },
}

const GIT_CARDS: Record<string, { description: string; code_example: string; exercise: string; difficulty: number; subtitle?: string }> = {
  'git init': { description: 'Inicializa um novo repositório Git no diretório atual.', code_example: 'git init\n# Initialized empty Git repository in /path/.git/', exercise: 'Crie um novo repositório Git em uma pasta vazia.', difficulty: 1, subtitle: 'Inicializa repositório' },
  'git clone': { description: 'Clona um repositório remoto para a máquina local.', code_example: 'git clone https://github.com/user/repo.git\ngit clone git@github.com:user/repo.git my-folder', exercise: 'Clone o repositório https://github.com/example/project para uma pasta chamada "proj".', difficulty: 1, subtitle: 'Clona repositório' },
  'git add': { description: 'Adiciona arquivos à staging area (prepara para commit).', code_example: 'git add arquivo.txt       # um arquivo\ngit add .                 # todos os arquivos\ngit add src/*.py          # padrão glob', exercise: 'Adicione todos os arquivos .py da pasta src/ à staging area.', difficulty: 1, subtitle: 'Adiciona à staging' },
  'git commit': { description: 'Salva as mudanças da staging area no histórico do repositório.', code_example: 'git commit -m "feat: adiciona login"\ngit commit -m "fix: corrige bug do carrinho"', exercise: 'Faça um commit com a mensagem "feat: adiciona página de perfil".', difficulty: 1, subtitle: 'Salva mudanças' },
  'git status': { description: 'Mostra o estado dos arquivos (modificados, staged, untracked).', code_example: 'git status\n# On branch main\n# Changes not staged for commit:\n#   modified:   README.md', exercise: 'Use git status para verificar quais arquivos foram modificados.', difficulty: 1, subtitle: 'Verifica status' },
  'git log': { description: 'Mostra o histórico de commits do repositório.', code_example: 'git log                     # histórico completo\ngit log --oneline          # uma linha por commit\ngit log --oneline -5       # últimos 5 commits', exercise: 'Use git log --oneline para ver os últimos 10 commits.', difficulty: 1, subtitle: 'Histórico de commits' },
  'git push': { description: 'Envia commits locais para o repositório remoto.', code_example: 'git push origin main\ngit push -u origin feature-branch  # primeira vez', exercise: 'Envie seus commits locais para a branch main do remoto.', difficulty: 1, subtitle: 'Envia para remoto' },
  'git pull': { description: 'Baixa e integra mudanças do repositório remoto.', code_example: 'git pull origin main\ngit pull --rebase origin main', exercise: 'Atualize sua branch local com as últimas mudanças do remoto.', difficulty: 1, subtitle: 'Baixa do remoto' },
  'git branch': { description: 'Lista, cria ou deleta branches.', code_example: 'git branch                  # lista branches\ngit branch feature-login    # cria branch\ngit branch -d feature-login # deleta branch', exercise: 'Crie uma nova branch chamada "dev" e liste todas as branches.', difficulty: 1, subtitle: 'Gerencia branches' },
  'git checkout': { description: 'Muda de branch ou restaura arquivos.', code_example: 'git checkout feature-login    # muda de branch\ngit checkout -b nova-branch   # cria e muda\ngit checkout -- arquivo.txt   # restaura arquivo', exercise: 'Crie e mude para uma branch chamada "hotfix/bug-123".', difficulty: 1, subtitle: 'Muda de branch' },
  'git switch': { description: 'Alternativa moderna ao checkout para mudar de branch.', code_example: 'git switch main\ngit switch -c feature-nova  # cria e muda', exercise: 'Use git switch para ir para a branch "develop".', difficulty: 1, subtitle: 'Alterna branch' },
  'git merge': { description: 'Combina duas branches, unindo seus históricos.', code_example: 'git checkout main\ngit merge feature-login', exercise: 'Mergie a branch "feature" na "main".', difficulty: 2, subtitle: 'Combina branches' },
  'git rebase': { description: 'Reaplica commits de uma branch sobre outra, criando histórico linear.', code_example: 'git checkout feature\ngit rebase main', exercise: 'Rebase sua branch feature na main para um histórico linear.', difficulty: 3, subtitle: 'Reorganiza commits' },
  'git stash': { description: 'Salva mudanças temporariamente sem commit.', code_example: 'git stash                    # salva mudanças\ngit stash list               # lista stashes\ngit stash pop                # restaura e remove\ngit stash apply              # restaura sem remover', exercise: 'Guarde suas mudanças temporárias com stash e depois restaure.', difficulty: 2, subtitle: 'Salva temporariamente' },
  'git reset': { description: 'Desfaz commits ou mudanças na staging area.', code_example: 'git reset HEAD arquivo.txt     # unstaged\ngit reset --soft HEAD~1       # desfaz commit, mantém staged\ngit reset --hard HEAD~1       # desfaz tudo', exercise: 'Use git reset --soft para desfazer o último commit mantendo as mudanças.', difficulty: 3, subtitle: 'Desfaz commits' },
  'git diff': { description: 'Mostra diferenças entre commits, branches ou working tree.', code_example: 'git diff                    # mudanças não staged\ngit diff --staged           # mudanças staged\ngit diff main..feature      # entre branches', exercise: 'Use git diff para ver as mudanças não staged no arquivo main.py.', difficulty: 1, subtitle: 'Mostra diferenças' },
  'git remote': { description: 'Gerencia conexões com repositórios remotos.', code_example: 'git remote -v                      # lista remotos\ngit remote add origin <url>      # adiciona remoto\ngit remote remove origin          # remove remoto', exercise: 'Adicione um remoto chamado "upstream" apontando para o repo original.', difficulty: 2, subtitle: 'Gerencia remotos' },
  'git cherry-pick': { description: 'Aplica um commit específico de outra branch na branch atual.', code_example: 'git cherry-pick abc1234\ngit cherry-pick abc1234 def5678', exercise: 'Aplique o commit abc1234 da branch develop na sua branch atual.', difficulty: 3, subtitle: 'Aplica commit específico' },
}

const CARD_MAPS: Record<string, Record<string, any>> = {
  Python: PYTHON_CARDS,
  SQL: SQL_CARDS,
  Pandas: PANDAS_CARDS,
  Git: GIT_CARDS,
}

function normalizeKey(s: string): string {
  return s.toLowerCase().trim().replace(/\s+/g, ' ')
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { front, language, code } = body

    if (code) {
      const lines = code.split('\n').filter((l: string) => l.trim())
      const detectedCards = []
      const langMap = CARD_MAPS[language] || {}
      for (const line of lines) {
        for (const [key, card] of Object.entries(langMap)) {
          if (line.toLowerCase().includes(key.toLowerCase().replace(/\(\)/g, ''))) {
            detectedCards.push({ front: key, ...card })
          }
        }
      }
      if (detectedCards.length > 0) {
        return NextResponse.json({ cards: detectedCards })
      }
      return NextResponse.json({ cards: [] })
    }

    const langCards = CARD_MAPS[language] || {}
    const key = normalizeKey(front)

    for (const [k, card] of Object.entries(langCards)) {
      if (normalizeKey(k) === key || normalizeKey(k).includes(key) || key.includes(normalizeKey(k))) {
        return NextResponse.json({ front: k, language, ...card })
      }
    }

    const fallback = {
      front,
      language,
      description: `Função/conceito de ${language}: ${front}`,
      code_example: `# ${front}\n# Adicione o exemplo aqui`,
      exercise: `Demonstre o uso de ${front} com um exemplo prático.`,
      difficulty: 2,
    }
    return NextResponse.json(fallback)
  } catch (error) {
    return NextResponse.json({ error: 'Failed to generate card' }, { status: 500 })
  }
}
